version: '3.8'

services:
  recorder:
    image: book000/youtube-live-recorder:1.6.1
    volumes:
      - type: bind
        source: ./data
        target: /data
    env_file:
      - recorder.env

  watch-new-movie:
    image: book000/youtube-live-recorder-watch-new-movie:1.6.0
    volumes:
      - type: bind
        source: ./data
        target: /data

  discord-deliver:
    image: book000/discord-deliver:v1.2.0
    env_file:
      - discord-deliver.env