name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: src/
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:$(date +%s)
