# 任意のレジストリに複数の Docker image を公開orビルドする。
# master/mainのプッシュ時、プルリクの作成・更新時、リリース時に動作する。

name: Docker

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  release:
    types:
      - published

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  job:
    name: Docker build (${{ fromJson(matrix.target).directory }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - '{ imageName: "book000/youtube-live-recorder", directory: "src" }'
          - '{ imageName: "book000/youtube-live-recorder-watch-new-movie", directory: "watch-new-movie" }'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ fromJson(matrix.target).directory }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ fromJson(matrix.target).directory }}-

      - name: Login to ${{ env.REGISTRY }}
        if: github.event_name == 'release'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ fromJson(matrix.target).imageName }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ fromJson(matrix.target).directory }}
          push: ${{ github.event_name == 'release' }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
