name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    name: hadolint
    uses: book000/templates/.github/workflows/reusable-hadolint-ci.yml@0973a96ab08cb4eb8820eaa5b35bde6d4f745118 # master
