name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    name: hadolint
    uses: book000/templates/.github/workflows/reusable-hadolint-ci.yml@f61066bfac67a45a325ea728191497763566dd23 # master
