name: hadolint

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  hadolint:
    name: hadolint
    uses: book000/templates/.github/workflows/reusable-hadolint-ci.yml@1f725b61fe3b897dde4fc3c02d8f9496d3cdb428 # master
